# -*- coding: utf-8 -*-
"""JavaTestMCPayment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_AeyyR1SPYa9I0wYYWLcK4rU0yvBkE1
"""

def numberOneBigO2(array):
  result = 0
  for i in range(0, len(array)):
    for j in range(0, len(array)):
      if (array[i]-array[j]) < 0:
        break
      else:
        result = array[i]
  return result

# Solusi yang sudah dioptimasi
def numberOneBigO(array):
  max = 0
  for element in array:
    if element > max:
      max = element
  return max

array = [3, 1, 4, 2]
array2 = [1, 2, 3, 4]

print(numberOneBigO2(array))
print(numberOneBigO2(array2))

print(numberOneBigO(array))
print(numberOneBigO(array2))

"""================================================================================"""

def numberTwo(array, x):
  result = []
  for i in range(0, len(array)):
    full_loop = False
    for j in range(0, len(array)):
      if (array[i]/array[j] == x):
        full_loop = False
        break
      else:
        full_loop = True
    if full_loop:
      result.append(array[i])
  return result

array = [1, 2, 3, 4]
x = 4
x2 = 1

print(numberTwo(array, x))
print(numberTwo(array, x2))

"""================================================================================"""

def numberThree(sentence, x):
  result = []
  for word in sentence.split():
    if len(word) == x:
      result.append(word)
  return result

sentence = "souvenir loud four lost"
x = 4
x2 = 8

print(numberThree(sentence, x))
print(numberThree(sentence, x2))

